service_name: user_service
grpc_server:
    port: :6002
    development: true
    timeout: 15
    read_timeout: 5
    write_timeout: 5
    max_connection_idle: 5
    max_connection_age: 5
logger:
    level: debug
    dev_mode: false
    encoder: json
database:
    host: localhost
    port: 5432
    user: db
    password: db
    name: user_db
    ssl_mode: disable
    db_driver: pgx
